name: model_map
version: 0.3.0
authors:
- Dan Parnham <dan@teadriven.me.uk>
- Diego Rocha <diego.rocha.comp@gmail.com>
description: Mirror based model mapping
homepage: http://github.com/parnham/model_map.dart
environment:
  sdk: '>=1.1.0-dev.4.0 <2.0.0'
dependencies:
  quiver: any
dev_dependencies:
  unittest: any
