name: morph
version: 0.8.0
authors:
- Diego Rocha <diego.rocha.comp@gmail.com>
- Dan Parnham <dan@teadriven.me.uk>
description: A mirror based serializer and deserializer of Dart objects
homepage: https://github.com/Dreckr/Morph
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  collection: '>=0.9.0 <1.0.0'
  quiver: '>=0.8.1'
dev_dependencies:
  unittest: '>=0.8.1'
